import type { Metadata } from "next";
import { PageFrame, SiteShell, externalLinks } from "../components/SiteShell";

export const metadata: Metadata = { title: "Work — D The Designer", description: "Case studies and shipped tools from D The Designer." };

const projects = [
  { id: "make-a-monster", title: "Adobe Firefly / Make a Monster", category: "AI creative workflow", role: "Visual workflow, comparison, documentation, and production", problem: "How do you turn generative exploration into a coherent visual development process instead of an image dump?", method: "Research and references → visual reduction → concept development → cross-model comparison → concept-drift correction → still-to-motion production.", result: "A documented 22-slide workflow that makes the decisions, comparisons, and production logic visible.", live: "/contact", action: "Discuss workflow →" },
  { id: "specimen-7b", title: "Specimen 7-B Product + Merch System", category: "Generative brand system / output evaluation", role: "Brand system, product direction, and curation", problem: "How do you move from one generated image to a usable, repeatable product and merchandise language?", method: "Build the visual language, test applications, then use KEEP / FIX / REJECT to separate promising output from production-ready output.", result: "A focused design system that treats selection and correction as part of the creative work.", live: "https://specimen-7b-system.d-the-designer.chatgpt.site/" },
  { id: "dead-carrier", title: "Dead Carrier", category: "Interaction / creative technology", role: "Creative direction, writing, interface, and implementation", problem: "How can an AI-assisted interactive-fiction workflow produce a complete, playable experience while keeping the writing and systems logic deliberate?", method: "Story structure → interface logic → implementation → opening sequence → playable delivery.", result: "A working Infocom-style text adventure with a clear relationship between narrative, rules, and interface.", live: "https://d-the-designer.github.io/Orphan-Sky-public-content/dead-carrier.html" },
  { id: "orphan-sky", title: "Orphan Sky", category: "Transmedia creative direction / visual systems", role: "Worldbuilding, visual development, and production language", problem: "How do you keep a large fictional world visually coherent across interfaces, artifacts, moving image, and narrative material?", method: "Visual grammar → interface language → design bible → artifacts → production pipeline → consistency review.", result: "A sustained worldbuilding practice framed as creative direction and transmedia systems, not as a standalone fictional universe.", live: "https://d-the-designer.github.io/Orphan-Sky-public-content/" },
  { id: "tools", title: "Working tools and conventional design", category: "UI/UX · graphic production · technical documentation", role: "Interface design, visual communication, and delivery", problem: "How do you make a small tool or visual system understandable, usable, and ready to leave the desktop?", method: "Information hierarchy → interface behavior → accessibility → implementation → testing → handoff.", result: "A body of shipped browser tools, identity, layout, UI, print, and documentation work available across the live tools and Behance archive.", live: externalLinks.behance },
] as const;

export default function WorkPage() {
  return <SiteShell current="work"><PageFrame className="subpage work-page"><div className="subpage-heading"><div><span className="eyebrow">Employment evidence</span><h1>Selected work</h1><p className="subpage-dek">A design technologist&apos;s working archive: systems-minded visual production from concept through quality control and deployment.</p></div><a href={externalLinks.behance} target="_blank" rel="noreferrer">See more on Behance →</a></div><div className="case-study-list">{projects.map((project) => <article className="case-study" id={project.id} key={project.title}><div className="case-study-heading"><div><span className="card-category">{project.category}</span><h2>{project.title}</h2></div><a className="small-primary" href={project.live} target={project.live.startsWith("http") ? "_blank" : undefined} rel={project.live.startsWith("http") ? "noreferrer" : undefined}>{"action" in project ? project.action : "Inspect work →"}</a></div><div className="case-study-facts"><div><strong>Problem</strong><p>{project.problem}</p></div><div><strong>My role</strong><p>{project.role}</p></div><div><strong>System / method</strong><p>{project.method}</p></div><div><strong>Result</strong><p>{project.result}</p></div></div></article>)}</div><section className="work-cta"><h2>Need a system that can survive real work?</h2><p>Bring me into a project when the challenge is part visual, part technical, and part operational.</p><a className="primary-button" href="/contact">Hire / contact me</a></section></PageFrame></SiteShell>;
}
