import type { Metadata } from "next";
import { PageFrame, SiteShell } from "../components/SiteShell";

<<<<<<< HEAD
export const metadata: Metadata = { title: "About — D The Designer", description: "About Dreia Wilson, Design Technologist and Visual Systems Designer." };

export default function AboutPage() {
  return <SiteShell current="about"><PageFrame className="subpage about-page"><section className="about-intro"><img className="headshot" src="/headshot.jpg" alt="Dreia Wilson" /><div><span className="eyebrow">D the Designer</span><h1>Dreia Wilson</h1><p className="about-lead">Design Technologist &amp; Visual Systems Designer working across visual systems, AI-assisted creative production, UI/UX, and creative technology.</p><p>My background includes graphic production, software QA, front-end work, interface design, technical documentation, and startup collaboration. I bring those disciplines into current generative workflows, where the hard problem is often not generating more material but selecting, controlling, documenting, and delivering usable work.</p><p>That means the work stays grounded in visual judgment: references, constraints, comparison, correction, consistency, accessibility, and production readiness. I design both the artifact and the system that produces, tests, outputs, and deploys it.</p><p>Based in the Bay Area, I am available for full-time roles, contract work, and selected collaborations.</p></div></section><section className="credentials-section"><h2>Current signals</h2><div className="credential-list"><Credential title="Adobe Firefly Ambassador">Current Adobe program work focused on generative AI creative workflows, reference anchoring, comparison, correction, and instructional communication.</Credential><Credential title="Creative Partner Programs">Verified creative partner relationships with ImagineArt, Pollo, and Vidu.</Credential><Credential title="Stages — Inaugural Member (The 100)">Inaugural member of Stages' founding cohort of 100.</Credential></div></section><section className="about-grid"><section><h2>Education</h2><p><strong>Diablo Valley College</strong><br />Associate degree · Graphic design, typography, animation, web, and production</p><p>Additional UI/UX, accessibility, and technical study continues alongside current practice.</p></section><section><h2>Earlier software QA &amp; technical documentation</h2><p><strong>1996–2000</strong></p><p>Formal software QA and documentation experience informs the way I approach current AI output evaluation, creative workflow testing, usability review, and production QA.</p></section></section><section className="also-building"><strong>Also building</strong><p>Orphan Sky and related worldbuilding work are a separate transmedia creative-direction practice. It shares the same discipline: visual grammar, systems, consistency, and delivery.</p></section></PageFrame></SiteShell>;
=======
export const metadata: Metadata = { title: "About — D The Designer", description: "About D The Designer, a graphic designer and creative technologist." };

export default function AboutPage() {
  return <SiteShell current="about"><PageFrame className="subpage about-page"><section className="about-intro"><img className="headshot" src="/headshot.jpg" alt="Dreia Wilson" /><div><h1>About</h1><p>I'm Dreia — but everyone calls me D, and most people know me as D the Designer. I'm a graphic designer and creative technologist based in the Bay Area, working at the intersection of traditional design discipline and generative AI. My background is production art: file versioning, brand systems, asset pipelines — the unglamorous infrastructure that makes creative work scale. That discipline is what I bring into every AI workflow I build now.</p><p>Today my focus is prompt design and multimodal systems: treating language as a design material with its own grammar, testing how phrasing shapes visual and behavioral output, and building the documentation and QA pipelines that make AI-assisted creative work repeatable instead of accidental. I'm an Adobe Firefly Creative Ambassador, a Creative Partner with ImagineArt, Pollo, and Vidu, and an inaugural member of Stages (The 100).</p><p>Whether it's a brand system, an interface, or a prompt library for a generative pipeline, the process is the same: define the structure, document the logic, and iterate until it holds up under real use. Systems thinking first, visuals second.</p><p>Outside client work, I've spent three decades-plus building a single sci-fi universe — proof, if nothing else, that I don't start things I don't intend to finish.</p></div></section><section className="credentials-section"><h2>Credentials</h2><div className="credential-list"><Credential title="Adobe Firefly Ambassador">Part of Adobe's Firefly Ambassador program, showcasing generative AI creative workflows built on Adobe's tools.</Credential><Credential title="Creative Partner — ImagineArt, Pollo, Vidu">Creative Partner Programs across three additional AI creative platforms — cross-platform standing, not tied to a single vendor.</Credential><Credential title="Stages — Inaugural Member (The 100)">Inaugural member of Stages, as part of its founding cohort of 100.</Credential></div></section><section className="also-building"><strong>Also building</strong><p>A separate worldbuilding practice — Orphan Sky and related IP — running alongside the design and AI-systems work. Different pitch, same range.</p></section></PageFrame></SiteShell>;
>>>>>>> github/main
}

function Credential({ title, children }: { title: string; children: string }) { return <div className="credential"><h3>{title}</h3><p>{children}</p></div>; }
