import type { Metadata } from "next";
import { PageFrame, SiteShell } from "../components/SiteShell";

export const metadata: Metadata = { title: "About — D The Designer", description: "About D The Designer, a graphic designer and creative technologist." };

export default function AboutPage() {
  return <SiteShell current="about"><PageFrame className="subpage about-page"><section className="about-intro"><img className="headshot" src="/headshot.jpg" alt="Dreia Wilson" /><div><h1>About</h1><p>I'm Dreia — but everyone calls me D, and most people know me as D the Designer. I'm a graphic designer and creative technologist based in the Bay Area, working at the intersection of traditional design discipline and generative AI. My background is production art: file versioning, brand systems, asset pipelines — the unglamorous infrastructure that makes creative work scale. That discipline is what I bring into every AI workflow I build now.</p><p>Today my focus is prompt design and multimodal systems: treating language as a design material with its own grammar, testing how phrasing shapes visual and behavioral output, and building the documentation and QA pipelines that make AI-assisted creative work repeatable instead of accidental. I'm an Adobe Firefly Creative Ambassador, a Creative Partner with ImagineArt, Pollo, and Vidu, and an inaugural member of Stages (The 100).</p><p>Whether it's a brand system, an interface, or a prompt library for a generative pipeline, the process is the same: define the structure, document the logic, and iterate until it holds up under real use. Systems thinking first, visuals second.</p><p>Outside client work, I've spent three decades-plus building a single sci-fi universe — proof, if nothing else, that I don't start things I don't intend to finish.</p></div></section><section className="credentials-section"><h2>Credentials</h2><div className="credential-list"><Credential title="Adobe Firefly Ambassador">Part of Adobe's Firefly Ambassador program, showcasing generative AI creative workflows built on Adobe's tools.</Credential><Credential title="Creative Partner — ImagineArt, Pollo, Vidu">Creative Partner Programs across three additional AI creative platforms — cross-platform standing, not tied to a single vendor.</Credential><Credential title="Stages — Inaugural Member (The 100)">Inaugural member of Stages, as part of its founding cohort of 100.</Credential></div></section><section className="also-building"><strong>Also building</strong><p>A separate worldbuilding practice — Orphan Sky and related IP — running alongside the design and AI-systems work. Different pitch, same range.</p></section></PageFrame></SiteShell>;
}

function Credential({ title, children }: { title: string; children: string }) { return <div className="credential"><h3>{title}</h3><p>{children}</p></div>; }
