import type { Metadata } from "next";
import { PageFrame, SiteShell } from "../components/SiteShell";

export const metadata: Metadata = { title: "About — D The Designer", description: "About D the Designer, a Design Technologist and Visual Systems Designer." };

export default function AboutPage() {
  return <SiteShell current="about"><PageFrame className="subpage about-page"><section className="about-intro"><img className="headshot" src="/headshot.jpg" alt="D the Designer" /><div><span className="eyebrow">D the Designer</span><h1>D the Designer</h1><p className="about-lead">Design Technologist &amp; Visual Systems Designer working across visual systems, AI-assisted creative production, UI/UX, and creative technology.</p><p>My background includes graphic production, software QA, front-end work, interface design, technical documentation, and startup collaboration. I bring those disciplines into current generative workflows, where the hard problem is often not generating more material but selecting, controlling, documenting, and delivering usable work.</p><p>That means the work stays grounded in visual judgment: references, constraints, comparison, correction, consistency, accessibility, and production readiness. I design both the artifact and the system that produces, tests, outputs, and deploys it.</p><p>Based in the Bay Area, I am available for full-time roles, contract work, and selected collaborations.</p></div></section><section className="credentials-section"><h2>Current signals</h2><div className="credential-list"><Credential title="Adobe Firefly Ambassador">Current Adobe program work focused on generative AI creative workflows, reference anchoring, comparison, correction, and instructional communication.</Credential><Credential title="Creative Partner Programs">Verified creative partner relationships with ImagineArt, Pollo, and Vidu.</Credential><Credential title="Stages — Inaugural Member (The 100)">Inaugural member of Stages' founding cohort of 100.</Credential></div></section><section className="about-grid"><section><h2>Education</h2><p><strong>Diablo Valley College</strong><br />Associate degree · Graphic design, typography, animation, web, and production</p><p>Additional UI/UX, accessibility, and technical study continues alongside current practice.</p></section><section><h2>Earlier software QA &amp; technical documentation</h2><p><strong>1996–2000</strong></p><p>Formal software QA and documentation experience informs the way I approach current AI output evaluation, creative workflow testing, usability review, and production QA.</p></section></section><section className="also-building"><strong>Also building</strong><p>Orphan Sky and related worldbuilding work are a separate transmedia creative-direction practice. It shares the same discipline: visual grammar, systems, consistency, and delivery.</p></section></PageFrame></SiteShell>;
}

function Credential({ title, children }: { title: string; children: string }) { return <div className="credential"><h3>{title}</h3><p>{children}</p></div>; }
