import type { Metadata } from "next";
import { ArrowLink, PageFrame, SiteShell } from "./components/SiteShell";
import { HeroCarousel } from "./components/HeroCarousel";

export const metadata: Metadata = { title: "D The Designer — Design + AI systems", description: "Design and AI systems for creative teams building with generative tools." };

const featured = [
  { title: "Adobe Firefly / Make a Monster", category: "AI creative workflow", blurb: "A documented visual workflow spanning research, reference gathering, concept development, cross-model comparison, consistency management, and still-to-motion production.", live: "#make-a-monster" },
  { title: "Specimen 7-B", category: "Generative brand system", blurb: "A product and merchandise system built from a generated image, with KEEP / FIX / REJECT evaluation to turn exploration into controlled output.", live: "#specimen-7b" },
  { title: "Dead Carrier", category: "Interaction / creative technology", blurb: "An Infocom-style text adventure built with Claude — a working example of narrative systems, interface logic, and shipped interactive production.", live: "https://d-the-designer.github.io/Orphan-Sky-public-content/dead-carrier.html" },
];

export default function Home() {
  return <SiteShell current="home"><PageFrame className="home-page">
    <section className="identity-hero" aria-labelledby="identity-heading"><div className="identity-kicker">D THE DESIGNER</div><h1 id="identity-heading">D the Designer</h1><p className="identity-title">Design Technologist &amp; Visual Systems Designer</p><p className="identity-disciplines">Graphic Design · UI/UX · AI Production · Creative Technology</p><p className="identity-proposition">I build visual systems and AI-assisted creative workflows from concept through production, testing, documentation, and delivery.</p><div className="button-row"><a className="primary-button" href="#selected-work">View selected work</a><a className="secondary-button" href="/contact">Contact me</a></div><p className="resume-note">Résumé available on request · Open to full-time, contract, and selected collaborations.</p></section>
    <HeroCarousel />
    <section className="credentials-strip" aria-label="Selected partnerships and programs"><div><strong>Adobe Firefly Ambassador</strong></div><div><strong>Creative Partner</strong><span>ImagineArt</span></div><div><strong>Creative Partner</strong><span>Pollo</span></div><div><strong>Creative Partner</strong><span>Vidu</span></div><div><strong>Inaugural Member</strong><span>Stages (The 100)</span></div></section>
    <section className="home-section" id="selected-work"><div className="section-heading"><h2>Selected work</h2><ArrowLink href="/work" secondary>See all work</ArrowLink></div><div className="featured-grid">{featured.map((project) => <article className="featured-card" key={project.title}><span className="card-category">{project.category}</span><h3>{project.title}</h3><p>{project.blurb}</p><div className="card-links"><a href={project.live} target={project.live.startsWith("#") ? undefined : "_blank"} rel={project.live.startsWith("#") ? undefined : "noreferrer"}>{project.live.startsWith("#") ? "Read case study →" : "Try it live →"}</a><a href="/contact" className="muted-link">Bring me into a project</a></div></article>)}</div></section>
    <section className="capabilities-section"><div className="section-heading"><h2>What I solve</h2><span className="section-aside">Concept → production → review → delivery</span></div><div className="capabilities-grid"><Capability title="Visual systems & graphic production">Typography, identity, layout, templates, asset systems, and production-ready output.</Capability><Capability title="AI creative production">Generative workflows, multimodal tools, visual iteration, model comparison, and output refinement.</Capability><Capability title="Creative technology">AI-assisted prototyping, custom GPTs, lightweight interactive tools, and creative software workflows.</Capability><Capability title="UI/UX & interface design">Interaction logic, accessibility, responsive behavior, usability, and developer collaboration.</Capability><Capability title="Evaluation & QA">Instruction adherence, consistency review, edge cases, visual QA, usability review, and structured feedback.</Capability><Capability title="Documentation & production systems">Style guides, templates, file architecture, versioning, export specifications, accessibility, and delivery readiness.</Capability></div></section>
    <section className="freebie-teaser"><div><span className="eyebrow">Freebie</span><h2>AI Prompt Compendium</h2><p>A searchable library of working prompts, plus a blank version anyone can fill with their own — no install, works offline.</p></div><a className="primary-button" href="/freebies">See all freebies</a></section>
  </PageFrame></SiteShell>;
}

function Capability({ title, children }: { title: string; children: string }) { return <article className="capability"><h3>{title}</h3><p>{children}</p></article>; }
